### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ghost** [williamtdr/Steadfast#18]
Fatal error: Class 'Phar' not found in /imcpe/pvp/src/PocketMine-MP.php on line
24
rm: cannot remove `console.log': No such file or directory
Failed loading /root/vps/bin/php5/lib/php/extensions/no-debug-zts-20121212/opcac
he.so:  /root/vps/bin/php5/lib/php/extensions/no-debug-zts-20121212/opcache.so:
cannot open shared object file: No such file or directory

/root/vps/bin/ -> isnt even the right directory. whats wrong?

**Comment by MattWAnderson** [comment]
Is this on first install?

You need to install 1.4 PM and keep the bin folder to use steadfast.   You can email me directly on this if you need more help.

**Comment by ghost** [comment]
ahh ... i thought to use 1.3.12 bin.... thanks for the info :)
