### ISSUE TITLE
World Loading

### ISSUE THREAD

**Issue by ghost** [williamtdr/Steadfast#19]
It takes decades to load the world. is it normal?

**Comment by MattWAnderson** [comment]
Can you be more specific? 

Is this the first time a world has been loaded?

Does it ever load?

How long is a decade? :) (steadfast isn't 10 years old yet) 

Sorry to hassle, but the more we give for issues and information the easier to find the problem.

**Comment by MattWAnderson** [comment]
We find personally some users when changing gamemode and such will hang on the building terrain and cannot login until the player yml is deleted.   If this is what you mean?

**Comment by ghost** [comment]
building terrain takes me 2-3 minutes to load. most players cant even successfully connect due to poor spec devices.

**Comment by williamtdr** [comment]
Sorry, but I can't make progress from vague reports such as these. Please describe the environment you're in, what you expect to happen, and what does happen, then reopen the issue.
