### ISSUE TITLE
Shit doesn't work on Windows

### ISSUE THREAD

**Issue by iLel0** [williamtdr/Steadfast#23]
You can't get SteadFast working on Windows.
Out-of-the-box is the first error, doesn't work by than.
Even with replacing the src i get this error: /bin/sh No such file or directory
Please make an executable Windows installer too. Thanks

**Comment by iLel0** [comment]
*Outofthebox = download, extract, work. Which isn't the case at SteadFast, while Pocketmine does that

**Comment by tnytown** [comment]
Please specify what exactly does not work. What steps did you take to start Steadfast? Which commit are you running off of? Are you sure you're using start.cmd?

**Comment by iLel0** [comment]
Using start.cmd, nothing happens. Even with Pocketmine's start.cmd. Only a flashing terminal window. Do you guys already have a precompiled Server / precompiled bins for windows (Server 2008x64) too, just like you did with the linuxj one? Thanks

**Comment by tnytown** [comment]
Well, if you're using start.sh on Windows, of course it won't work. Windows does not support bash/sh scripting by default. As for the start.cmd not working...I'm not sure about this. Most Steadfast users run this on Linux. Any Windows Steadfast users lurking want to chime in?

**Comment by jose-vm** [comment]
Yeah, I have the same issue.

**Comment by hiilikewiki** [comment]
I have Windows and used to use steadfast before Dev 1266 came out for Pocketmine. You should try anylizing the .phar file or the . yml be decompiling it.

**Comment by williamtdr** [comment]
please don't use windows, ever
